# fly.toml app configuration file generated for digital-twin-frontend on 2024-08-11T20:15:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "digital-twin-frontend"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[http_service.concurrency]]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/"
    protocol = "http"
    restart_limit = 0
    timeout = "5s"

[machine]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
